export const PRODUCTS_LOADED = "PRODUCTS_LOADED";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const PRODUCT_ADDED = "TASK_ADDED";
export const PRODUCT_UPDATED = "PRODUCT_UPDATED";
export const PRODUCT_DELETED = "PRODUCT_DELETED";
export const SHOW_ERROR = "SHOW_ERROR";
export const HIDE_ERROR = "HIDE_ERROR";
